name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - id: slack_message
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        payload: |
          {
            "text": "Build Start (Client)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
    - uses: actions/checkout@v3


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}


    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build React Client
      run: |
        yarn
        yarn run build

    # Create & Push docker image
    - name: Build and push Docker Image
      uses: docker/build-push-action@v2 
      with:
        push: true
        context: .
        file: docker/Dockerfile
        tags: |
          ghcr.io/ajou-coding-hub/client:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy K8s


    - name: onFailure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        update-ts: ${{ steps.slack_message.outputs.ts }}
        payload: |
          {
            "text": "Build Error (Client)",
            "attachments": [
              {
                "pretext": "Error occured",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Error"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


    - uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        update-ts: ${{ steps.slack_message.outputs.ts }}
        payload: |
          {
            "text": "Build Finish (Client)",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Completed"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}