name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        yarn
        yarn run build

    # Create & Push docker image
    - name: Build and push
      uses: docker/build-push-action@v2 
      with:
        context: ./docker/Dockerfile
        push: true
        tags: thswlsgur98/app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy K8s
