name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: k8s

    steps:
    - id: slack_message
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        payload: |
          {
            "text": "Build Start (Client)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  },
                  {
                    "title": "URL",
                    "short": true,
                    "value": "${{ github.server_url }}/${{ github.repository }}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "${{ github.ref }}"
                  },
                  {
                    "title": "Sha",
                    "short": true,
                    "value": "${{ github.sha }}"
                  },
                  {
                    "title": "Commits",
                    "value": "${{ github.event.push.commits.*.message }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
    - uses: actions/checkout@v3
    

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders
        config-inline: |
          [registry."registry.container-registry.svc.cluster.local:5000"]
            http = true
            insecure = true
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Yarn
      run: |
        npm i yarn -g
        
    - name: Build React Client
      run: |
        yarn
        yarn run build

    # Create & Push docker image
    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: docker/Dockerfile
        tags: |
          registry.container-registry.svc.cluster.local:5000/client:latest
        cache-from: type=registry,ref=registry.container-registry.svc.cluster.local:5000/client:buildcache
        cache-to: type=registry,ref=registry.container-registry.svc.cluster.local:5000/client:buildcache,mode=max

    # Deploy K8s
    - name: Deploy K8s
      run: |
        microk8s kubectl apply -f ./k8s/deployment.yml


    - name: onFailure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        update-ts: ${{ steps.slack_message.outputs.ts }}
        payload: |
          {
            "text": "Build Error (Client)",
            "attachments": [
              {
                "pretext": "Error occured",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Error"
                  },
                  {
                    "title": "URL",
                    "short": true,
                    "value": "${{ github.server_url }}/${{ github.repository }}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "${{ github.ref }}"
                  },
                  {
                    "title": "Sha",
                    "short": true,
                    "value": "${{ github.sha }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


    - uses: slackapi/slack-github-action@v1.23.0
      with:
        # The following message update step does not accept a channel name.
        # Setting a channel ID here for consistency is highly recommended.
        channel-id: "C0468FV9M63"
        update-ts: ${{ steps.slack_message.outputs.ts }}
        payload: |
          {
            "text": "Build Finish (Client)",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Completed"
                  },
                  {
                    "title": "URL",
                    "short": true,
                    "value": "${{ github.server_url }}/${{ github.repository }}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "${{ github.ref }}"
                  },
                  {
                    "title": "Sha",
                    "short": true,
                    "value": "${{ github.sha }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
